name = "medium"
main = "src/index.ts"
compatibility_date = "2025-01-04"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzIyMGFmNTctZWE4ZC00MzM1LWFhMWQtMGZhMzBmNmY5NGE0IiwidGVuYW50X2lkIjoiODYwNzEwNjIzZjIzYjE2ODE2NWEzNjU2ZjA3YzJmYmQxNWRiMGEwOGFlMWZjMjQxZjVjZjg3YjI4MDVmOGUyMSIsImludGVybmFsX3NlY3JldCI6IjNlYzE4YjVhLTM4NzEtNDliNC1iY2MxLTFhZDlmYzI5ZWQ3NCJ9.IEZr6aM-lrvY5pJ_TFMbBsM9EDmKKNEFoJWG2b2Vw8Y"

JWT_SECRET = "whhdbh2739db93938drb39"